default: &default
  adapter: 'mysql2'
  pool:    5
  timeout: 5000

local: &local
  host:     '127.0.0.1'
  username: 'root'
  password: 'password'

job_posting:
  <<: *default
  <<: *local
  database: '__JOB_POSTING__'

oauth:
  <<: *default
  <<: *local
  database: 'oauth2.0'

default_env:
  <<: *default
  <<: *local
